version: '3.4'

services:
  frontend:
    build: .
    image: 'vue_frontend'
    container_name: "vue_frontend"
    network_mode: "bridge"
    volumes:
      - ./:/workspace/vue_frontend
    ports:
      - 3000:3000
      - 4173:4173
    command: tail -f /bin/sh
